# Generated by Django 5.0 on 2024-02-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_cusorders'),
    ]

    operations = [
        migrations.CreateModel(
            name='CusRatingsFeedbacks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.IntegerField(default=100)),
                ('ratings', models.FloatField(default=0.0)),
                ('feedbacks', models.TextField(default='feedbacks', max_length=500)),
                ('username', models.CharField(default='username', max_length=100)),
            ],
        ),
    ]
