# Generated by Django 5.0 on 2023-12-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.flaticon.com%2Ffree-icon%2Fplaceholder_1377194&psig=AOvVaw36RW-RSFevjrLkYoSmYb3-&ust=1703071266366000&source=images&cd=vfe&ved=0CBIQjRxqFwoTCMCBj4qxm4MDFQAAAAAdAAAAABAJ', max_length=500),
        ),
    ]
