# Generated by Django 5.0 on 2023-12-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_alter_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(default='Dhoni finish off in style India lift the World Cup After 28 year party start in dressing room the indian captain icriduble', max_length=500),
        ),
    ]
