# Generated by Django 5.0 on 2024-01-31 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_history'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='operations_type',
            new_name='operation_type',
        ),
    ]
